### ISSUE TITLE
CTRL + E blocks this shortcut system-wide

### ISSUE THREAD

**Issue by Myhall** [CennoxX/KeePass-QuickSearch#5] opened 2024-10-08 09:20 UTC
Version: 2.40
OS: Windows 11

When using plugin v. 2.40 and hitting CTRL + E anywhere in windows without even having focus on KeePass, the shortcut is processed by Keepass and not by the focused window. The quicksearch box gets focus in the keepass, but the Keepass itself does not.
This effectively blocks the CTRL + E shortcut across the system and makes the plugin unusable.

**Comment by Myhall** [comment] 2024-10-08 09:26
Keepass v. 2.57 (64-bit)

**Comment by CennoxX** [comment] 2024-10-08 10:06
Duplicate of #3 this will be released soon.
Here is an internal build of this solution: https://github.com/CennoxX/KeePass-QuickSearch/actions/runs/11201172896

**Closed by CennoxX** 2024-10-08 10:06 UTC
